version = "3.10.7"

project.includeFilters = [
  "src/.*"
]

runner.dialect = scala213

maxColumn = 120
align.preset = most
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings.style = SpaceAsterisk
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true

align.tokens.add = [
  {
    code = ":"
  },
  {
    code = ":="
  },
  {
    code = "="
  }
  
]

newlines.beforeCurlyLambdaParams = "never"
newlines.alwaysBeforeMultilineDef = false
newlines.implicitParamListModifierForce = [before]

verticalMultiline.atDefnSite = true

optIn.annotationNewlines = true

rewrite.rules = [SortImports, PreferCurlyFors, AvoidInfix]

indent.main = 4
indent.significant = 4
